import Head from 'next/head'
import Flight from '../components/Flight'
import Header from '../components/Header'
import Background from '../custom/Background'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background/>
      <Header/>
      <Flight/>
    </div>
  )
}
